1724784854981	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1724809040961	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1724809040961	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1724809040962	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1724809040964	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1724809041042	Sync.SyncScheduler	DEBUG	Woke from sleep.
1724809041043	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1724809041043	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1724809041043	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1724809043044	Sync.Service	DEBUG	User-Agent: Firefox/129.0.1 (Linux x86_64) FxSync/1.131.0.20240812083845.desktop
1724809043044	Sync.Service	INFO	Starting sync at 2024-08-27 20:37:23 in browser session ajjXmy1XBYSm
1724809043044	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1724809043046	Sync.Status	INFO	Resetting Status.
1724809043047	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1724809043047	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1724809043047	FirefoxAccounts	DEBUG	getOAuthToken enter
1724809043047	FirefoxAccounts	TRACE	getCachedToken returning cached token
1724809043047	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1724809043048	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1724809043048	Sync.SyncAuthManager	INFO	Getting sync key
1724809043048	FirefoxAccounts	DEBUG	getOAuthToken enter
1724809043048	FirefoxAccounts	TRACE	getCachedToken returning cached token
1724809043048	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1724809043049	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1724809043049	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1724809043049	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1724809043049	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1724809043051	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1724809043052	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1724809043052	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1724809043052	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1724809043052	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1724809043052	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1724809043053	FirefoxAccounts	TRACE	Getting command keys: https://identity.mozilla.com/cmd/open-uri
1724809043053	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1724809043053	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1724809043054	FirefoxAccounts	TRACE	Getting command keys: https://identity.mozilla.com/cmd/close-uri/v1
1724809043057	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/214229003/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1724809043057	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1724809043057	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1724809043057	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1724809043057	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1724809043058	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1724809043061	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
